version: '3'

services:
  app:
    build:
      context: .
    ports:
      -  "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - rabbitmq
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" # Default Port
      - "15672:15672" # For UI
    expose:
      - "15672"

  celery:
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A config worker --loglevel=DEBUG & > celery_log
    depends_on:
      - rabbitmq