version: '3'

services:
  app:
    build:
      context: .
    ports:
      -  "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
      
  redis:
    image: redis:7.2.3

  celery:
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A app worker -l INFO
    depends_on:
      - redis