# Generated by Django 4.2.11 on 2024-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
