# Generated by Django 4.2.11 on 2024-08-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_valid',
        ),
    ]
