# Generated by Django 4.2.11 on 2024-08-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_delivery_is_valid_remove_item_is_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
            preserve_default=False,
        ),
    ]
