# Generated by Django 4.2.11 on 2024-03-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
