# Generated by Django 4.2.11 on 2024-08-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_items_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='receiver',
        ),
    ]
