# Generated by Django 4.2.11 on 2024-08-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_delivery_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='sender',
        ),
    ]
