# Generated by Django 4.2.11 on 2024-03-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'departure'), ('2', 'arrival')], default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
