# Generated by Django 4.2.11 on 2024-03-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_nickname',
            field=models.CharField(max_length=32, verbose_name='Kakao Nickname'),
        ),
    ]
