# Generated by Django 4.2.11 on 2024-03-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='user_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.IntegerField(verbose_name='kakao_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_nickname',
            field=models.CharField(max_length=32, verbose_name='nickname'),
        ),
    ]
