# Generated by Django 4.2.11 on 2024-03-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_user_id_alter_user_kakao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.IntegerField(null=True, verbose_name='kakao_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_nickname',
            field=models.CharField(max_length=32, null=True, verbose_name='nickname'),
        ),
    ]
